apiVersion: v1
kind: Service
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  selector:
    app: airflow-webserver
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30000   
  type: NodePort  
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-webserver
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      initContainers:
        - name: fix-permissions
          image: alpine
          command:
            - sh
            - -c
            - |
              echo "Configurando SSH..."
              mkdir -p /tmp/home/.ssh
              cp /etc/git-secret/gitSshKey /tmp/home/.ssh/id_rsa
              cp /etc/git-secret/known_hosts /tmp/home/.ssh/known_hosts
              chmod 600 /tmp/home/.ssh/id_rsa
              chmod 644 /tmp/home/.ssh/known_hosts
              chown -R 65533:65533 /tmp/home/.ssh  
          volumeMounts:
            - name: git-secret-volume
              mountPath: /etc/git-secret
              readOnly: true
            - name: tmp-home
              mountPath: /tmp/home

        - name: init-airflow-db
          image: viniciusotoni/custom-airflow-image
          command: ["airflow", "db", "init"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_URL
        - name: create-airflow-user
          image: viniciusotoni/custom-airflow-image:latest
          imagePullPolicy: Always
          command:
            - "sh"
            - "-c"
            - >
              airflow users list | grep $(AIRFLOW_ADMIN_USERNAME) || \
              airflow users list | grep $(AIRFLOW_EMAIL) || \
              airflow users create --username $(AIRFLOW_ADMIN_USERNAME) --password $(AIRFLOW_ADMIN_PASSWORD)
              --firstname User --lastname User --email $(AIRFLOW_EMAIL) --role Admin
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_URL
            - name: AIRFLOW_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_ADMIN_USERNAME
            - name: AIRFLOW_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_ADMIN_PASSWORD
            - name: AIRFLOW_EMAIL
              valueFrom:
                secretKeyRef:
                  name: airflow-secrets
                  key: AIRFLOW_EMAIL
      containers:
        - name: webserver
          image: viniciusotoni/custom-airflow-image
          ports:
            - containerPort: 8080
          command: ["airflow", "webserver"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: KubernetesExecutor
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: POSTGRES_URL
            - name: AIRFLOW__CORE__DAGS_FOLDER
              value: /opt/airflow/dags
          volumeMounts:
            - mountPath: /opt/airflow
              name: airflow-data
            - mountPath: /opt/airflow/dags  
              name: airflow-dags  
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"

        - name: git-sync
          image: k8s.gcr.io/git-sync:v3.1.2
          env:
            - name: HOME
              value: /tmp/home
          args:
            - "--repo=git@github.com:ViniciusOtoni/Dags-Datamaster.git"
            - "--branch=main"
            - "--root=/git"
            - "--dest=dags"
            - "--ssh"
            - "--ssh-key-file=/tmp/home/.ssh/id_rsa"
            - "--ssh-known-hosts-file=/tmp/home/.ssh/known_hosts"
            - "--wait=3600"
          volumeMounts:
            - name: airflow-dags
              mountPath: /git
            - name: tmp-home
              mountPath: /tmp/home
            - name: git-secret-volume
              mountPath: /etc/git-secret
              readOnly: true

      volumes:
        - name: airflow-data
          emptyDir: {}
        - name: airflow-dags
          emptyDir: {}
        - name: tmp-home
          emptyDir: {}
        - name: git-secret-volume
          secret:
             secretName: airflow-git-ssh-secret

